### ISSUE TITLE
How to install it exactly?

### ISSUE THREAD

**Issue by vanabel** [INL/BlackLab-server#1]
I have installed tomcat on my server, but when I try to install the BlackLab-server as BlackLab use `mvn install`, it fails, 
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:23.298s
[INFO] Finished at: Sat Sep 12 18:38:25 CST 2015
[INFO] Final Memory: 7M/18M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project blacklab-server: Could not resolve dependencies for project nl.inl.blacklab:blacklab-server:war:1.2-SNAPSHOT: Could not find artifact nl.inl.blacklab:blacklab:jar:1.2-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```
Did I do something wrong? 

I want to get the `.war` file, is there another way?

**Comment by jan-niestadt** [comment]
You need [BlackLab](https://github.com/INL/BlackLab) as well. Just clone it and run "mvn install", then the BlackLab Server build should succeed. At some point we'll publish BlackLab on the central repository so you don't need to build it manually. The [BlackLab website](http://inl.github.io/BlackLab/) explains how to index your data. Good luck!

**Comment by vanabel** [comment]
You mean BlackLab infact include Black-server already? and I need't clone Black-server git, just run 'mvn install' in BlackLab will install Black-server also?

If so, how could I know that Black-server work?

**Comment by jan-niestadt** [comment]
No, they are two separate projects. When you run 'mvn install' on BlackLab, it builds the JAR and installs it in your local Maven repo ('mvn install' does not mean 'install the application', but 'install the artifact to the local repository'). Then when you run 'mvn package' on BlackLab-server, it builds the WAR. You have to install that manually, see [here](https://github.com/INL/BlackLab-server/wiki/BlackLab-Server-overview#Installation).

Before you can test BlackLab-server, you should index some data. That's done from the commandline using the BlackLab JAR, see [here](http://inl.github.io/BlackLab/getting-started.html) as I said. Over time we'll further streamline this process, but for now this should be enough to get you started. Good luck, and let me know if you get stuck.

**Comment by vanabel** [comment]
Hi, thanks for the explaination, I finally almost got it to work.

1. git clone the BlackLab, and install it with mvn install, I will get the blacklab-version.jar, after I saw it Build success, I also `create` index of Brown corpus (to dir `BlackLab/index-test/`), and I can test the `query` successfully (command line). So, as you can see,  **the BlackLab install & test has no problem**;
2. I also want to interface the query with web, so I need to install BlackLab-server, I just do the same thing as BlackLab, just clone it, and install it with mvn install, this time I succeed to get the `war` file in `target` dir. Then I follow your instruction: first create a configure file in `/etc/blacklab/blacklab-server.json`, which contains the index path:
```
 {
   "indexCollections": [
     "/home/pi/blacklab/BlackLab/index-test"
   ]
 }
```
Then I make a softlink of the server `war` file to the location of `Tomcat/webapps`, After I restart the tomcat7, there is a new created dir `blacklab-server`, which contains the contents of webs. 
3. I first enconter the problem of java version; I use java8 for mvn, as you can see:
```
# mvn -V
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.8.0, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre

```
It seems that tomac7 not automatically use java8, so I need to change the JAVA_HOME to be `/usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre` (which is configured in my Raspberry pi in the dir:`/etc/default/tomcat7`), then the issue of java version is solved;
4. The problem is, I still get the following error, when I visit `http://mydomain.com:8080/blacklab-server/`,
```
type Exception report

message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

java.lang.NullPointerException
	nl.inl.blacklab.server.search.SearchManager.isDebugMode(SearchManager.java:1396)
	nl.inl.blacklab.server.requesthandlers.RequestHandler.handle(RequestHandler.java:73)
	nl.inl.blacklab.server.BlackLabServer.doGet(BlackLabServer.java:136)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:722)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.28 logs.
```
Is this mean that the app can't run in java8?

**Comment by jan-niestadt** [comment]
You've found a bug! I will fix it soon, but for now, you can work around it by adding a setting "debugModeIps" to your blacklab-server.json file. The file should look like this:

<pre>
{
   "indexCollections": [
     "/home/pi/blacklab/BlackLab/index-test"
   ],

   "debugModeIps": [
      "127.0.0.1",      // IPv4 localhost
      "0:0:0:0:0:0:0:1" // IPv6 localhost
   ]
}</pre>

This setting indicates that requests coming from these IP addresses are handled in debug mode, which means you can get some extra info from the server and output is prettyprinted by default. It should be optional, but as you've found, bad things happen without it.

Java 8 should be no problem, BTW. Hopefully things will run without problems now. Cool that you're running it on the Pi by the way!

**Comment by vanabel** [comment]
Still other problems, when I add the local ips to use debugmod, the first error has solved and black-server can list a raw xml infomation. 

But when I try to search with `http://mydomain.com/blacklab-server/test-index/hits?patt=%22test%22`, it gives the following error:
```
java.lang.NullPointerException
	nl.inl.blacklab.server.search.SearchManager.search(SearchManager.java:1154)
	nl.inl.blacklab.server.search.SearchManager.searchHitsWindow(SearchManager.java:1076)
	nl.inl.blacklab.server.requesthandlers.RequestHandlerHits.handle(RequestHandlerHits.java:121)
	nl.inl.blacklab.server.requesthandlers.RequestHandler.handle(RequestHandler.java:244)
	nl.inl.blacklab.server.BlackLabServer.doGet(BlackLabServer.java:136)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
```

**Comment by jan-niestadt** [comment]
Sorry about that! But that's why it's still in beta I guess. I've fixed both problems and pushed them to GitHub, so if you perform a "git pull" and rebuild, it should - in theory - work now. If not, let me know. Thanks for reporting!

**Comment by vanabel** [comment]
Hi, After I use the [complete configure file](https://github.com/INL/BlackLab-server/wiki/BlackLab-Server-overview#appendix-a-configuration-file-blacklab-serverjson), then it works with out error.

**Comment by vanabel** [comment]
BTW, is there any stylesheet to make the raw xml  file looks good?
