### ISSUE TITLE
Any stylesheet for the raw xml outputs?

### ISSUE THREAD

**Issue by vanabel** [INL/BlackLab-server#2]
Finally, I got the **raw xml data** of search query of BlackLab-server with PHP, I am wondering is there any stylesheet, as an example, to make it looks better?

Or if I need to design it, is there any document to help me with this?

**Comment by vanabel** [comment]
Ok, I see, the raw data is good enough, I can format them by php.

**Comment by jan-niestadt** [comment]
Sorry, there's no example stylesheets included yet. I'd like to eventually include a sample search application that includes such stylesheets. Maybe in a few months. Glad you got it to work though!
