### ISSUE TITLE
update index data in realtime

### ISSUE THREAD

**Issue by vanabel** [INL/BlackLab-server#3]
I finally got to do the following thing:
1. Input a sentense, and submit it to the openconvert webpage;
2. Then we get the tei format corpus in RAW xml style;
3. write the raw xml contents into a local file;
4. use `IndexTool` to create index of the tei corpus;
5. query the new added sentense.

In the final step, I want to know is BlackLab-server can discover the updated index (all index are putted in a index directory collation) automatically? I find that I need to reboot `tomcat7` in order to use the new added index. 

I also find there is a configuation paramenter called `clientCacheTimeSec`, I try to change it into 60, which means we are cached for `60` secs, did this affect the realtime update index (I mean I can use the new index after 60s?)

**Comment by jan-niestadt** [comment]
Sorry about the delay in answering, I was at home with the flu. Right now, BlackLab Server does automatically discover newly added or removed indices, but updated indices not yet. You can either restart Tomcat like you said, or redeploy BLS ("touch" the blacklab-server.war file, or use Tomcat's admin interface).

The client cache time setting controls how long the client (i.e. the user's browser) will keep a result page from BLS in the page cache. Obviously, client-side caching can interfere with updates to the index, as the client might have some old and some new results.
