### ISSUE TITLE
Jsonp error handling

### ISSUE THREAD

**Issue by emanjavacas** [INL/BlackLab-server#5]
I am having some troubles trying to handle a jsonp error response. From my understanding, given that jsonp relies on external ```<script>``` fetching  (instead of xhr), errors thrown during fetching are all treated as parse errors, which means that the jsonp error response never reaches the client. Normally, jsonp requests in libraries (JQuery, goog.closure) implement error catching by means of a timeout, but in any case the error response script is lost. However, for an application as blacklab-server it seems crucial to know the reason of the error (which in many cases it can be due to an amendable user input error).
I don't know if it is standard practice, but a solution that comes to mind is returning a valid 200 response and only specifying that there was an error in the response payload, the client code could always consume this by very simple response checking and handle structured error information accordingly.
But maybe I am missing something in the entire jsonp story :-)

best,

**Comment by emanjavacas** [comment]
here is a fiddle illustrating the issue (substitute BASE with a valid url, the error is a missing quote in the value of "patt")

http://jsfiddle.net/sdyyvsg4/

**Comment by jan-niestadt** [comment]
Thanks, I never realised this. We don't use JSONP ourselves, so I never ran into this problem. I've fixed this in the dev branch; I hope you don't mind testing it there? If everything works properly, I'll make a new release soon.

**Comment by emanjavacas** [comment]
perfect! tested on dev and works :-)
