### ISSUE TITLE
doc info returns UNKNOWN_OPERATION error

### ISSUE THREAD

**Issue by emanjavacas** [INL/BlackLab-server#8]
```curl -X GET http://server/blacklab-server-1.4-SNAPSHOT/brown-tei/docs/0/infos```

gives 

```<?xml version="1.0" encoding="utf-8" ?><blacklabResponse><error><code>UNKNOWN_OPERATION</code><message>Unknown operation. Check your URL.</message></error></blacklabResponse>```

(I might be missing some configuration detail, but this is with the standard brown tei corpus)

**Comment by jan-niestadt** [comment]
Remove "/infos" from the URL, then it should work. (docs/# returns the metadata, docs/#/contents returns the contents if the "contentViewable" setting in indexmetadata.json is set to true).

**Comment by jan-niestadt** [comment]
I see the documentation is wrong, I'll update it. Sorry.
